[project]
name = "mlops-inference-fastapi-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.127.1",
    "mcp[cli]>=1.25.0",
]
